version: '3.8'

services:
  bot:
    build: .
    container_name: telegram_bot
    restart: always
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    volumes:
      - ./deepseek-ciberseguridad-lora:/app/deepseek-ciberseguridad-lora
